---
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=.bandit.yaml
        additional_dependencies:
          - pbr
        files: ^aioflo/.+\.py$
  - repo: https://github.com/python/black
    rev: 26.5.1
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        language_version: python3
        files: ^((aioflo|examples|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        args:
          - --skip="./.*,*.json"
          - --quiet-level=4
          - --ignore-words-list=thirdparty
        exclude_types: [json]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-docstrings
          - pydocstyle
        files: ^aioflo/.+\.py$
  - repo: https://github.com/PyCQA/isort
    rev: 9.0.1
    hooks:
      - id: isort
        additional_dependencies:
          - toml
        files: ^(aioflo|examples|tests)/.+\.py$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
      - id: mypy
        files: ^aioflo/.+\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=main
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        files: ^((aioflo|examples|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: shellcheck
        files: ^script/.+
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus
