"""Define constants for use in tests."""
TEST_ACCOUNT_ID = "aabbccdd"
TEST_DEVICE_ID = "98765"
TEST_EMAIL_ADDRESS = "email@address.com"
TEST_FIRST_NAME = "Tom"
TEST_LAST_NAME = "Jones"
TEST_LOCATION_ID = "mmnnoopp"
TEST_MAC_ADDRESS = "12:34:56:ab:cd:ef"
TEST_PASSWORD = "password"
TEST_PHONE_NUMBER = "+1 123-456-7890"
TEST_TOKEN = "123abc"
TEST_USER_ID = "12345abcde"

RESPONSE_ALARMS = {
    "items": [
        {
            "id": 3,
            "name": "health_test_skipped",
            "displayName": "Health Test Skipped",
            "description": "Health Test Skipped",
            "severity": "info",
            "isInternal": False,
            "isShutoff": False,
            "sendWhenValveIsClosed": True,
            "userActions": {
                "displayTitle": "Clear this Alert",
                "displayDescription": "Do you want to ignore this alert if it happens again?",
                "actions": [],
            },
            "actions": [],
            "supportOptions": [],
            "active": False,
            "children": [],
            "deliveryMedium": {
                "userConfigurable": False,
                "sms": {
                    "supported": True,
                    "defaultSettings": [
                        {"systemMode": "home", "enabled": False, "supported": True},
                        {"systemMode": "away", "enabled": False, "supported": True},
                        {"systemMode": "sleep", "enabled": False, "supported": True},
                    ],
                },
                "email": {
                    "supported": True,
                    "defaultSettings": [
                        {"systemMode": "home", "enabled": True, "supported": True},
                        {"systemMode": "away", "enabled": True, "supported": True},
                        {"systemMode": "sleep", "enabled": True, "supported": True},
                    ],
                },
                "push": {
                    "supported": True,
                    "defaultSettings": [
                        {"systemMode": "home", "enabled": True, "supported": True},
                        {"systemMode": "away", "enabled": True, "supported": True},
                        {"systemMode": "sleep", "enabled": True, "supported": True},
                    ],
                },
                "call": {
                    "supported": False,
                    "defaultSettings": [
                        {"systemMode": "home", "enabled": False, "supported": False},
                        {"systemMode": "away", "enabled": False, "supported": False},
                        {"systemMode": "sleep", "enabled": False, "supported": False},
                    ],
                },
            },
            "tags": [],
            "userFeedbackFlow": [],
        }
    ]
}

RESPONSE_LOCATION_INFO_BASE = {
    "id": TEST_LOCATION_ID,
    "users": [{"id": TEST_USER_ID}],
    "devices": [{"id": TEST_DEVICE_ID, "macAddress": "123456abcdef"}],
    "userRoles": [{"userId": TEST_USER_ID, "roles": ["owner"]}],
    "address": "123 Main Street",
    "city": "Boston",
    "state": "MA",
    "country": "us",
    "postalCode": "12345",
    "timezone": "US/Easter",
    "gallonsPerDayGoal": 240,
    "occupants": 2,
    "stories": 2,
    "isProfileComplete": True,
    "nickname": "Home",
    "irrigationSchedule": {"isEnabled": False},
    "systemMode": {"target": "home"},
    "locationType": "sfh",
    "locationSize": "lte_4000_sq_ft",
    "waterShutoffKnown": "unsure",
    "indoorAmenities": [],
    "outdoorAmenities": [],
    "plumbingAppliances": ["exp_tank"],
    "notifications": {
        "pending": {
            "infoCount": 0,
            "warningCount": 1,
            "criticalCount": 0,
            "alarmCount": [{"id": 57, "severity": "warning", "count": 1}],
        }
    },
    "areas": {
        "default": [
            {"id": "xxxxx", "name": "Attic"},
            {"id": "xxxxx", "name": "Basement"},
            {"id": "xxxxx", "name": "Garage"},
            {"id": "xxxxx", "name": "Main Floor"},
            {"id": "xxxxx", "name": "Upstairs"},
        ],
        "custom": [],
    },
    "account": {"id": TEST_ACCOUNT_ID},
}

RESPONSE_LOCATION_INFO_EXPAND_LOCATIONS = {
    "id": TEST_LOCATION_ID,
    "users": [{"id": TEST_USER_ID}],
    "devices": [
        {
            "isConnected": True,
            "fwVersion": "4.2.4",
            "lastHeardFromTime": "2020-01-16T19:42:06Z",
            "fwProperties": {
                "alarm_home_high_flow_rate_shut_off_deferment": 300,
                "alarm_home_high_water_use_shut_off_deferment": 300,
                "alarm_home_long_flow_event_shut_off_deferment": 300,
                "alarm_shutoff_time_epoch_sec": -1,
                "alarm_snooze_enabled": True,
                "alarm_suppress_duplicate_duration": 300,
                "alarm_suppress_until_event_end": False,
                "data_flosense_force_retrain": 0,
                "data_flosense_status_interval": 1200,
                "data_flosense_verbosity": 1,
                "device_data_free_mb": 1464,
                "device_installed": True,
                "device_mem_available_kb": 292780,
                "device_rootfs_free_kb": 802604,
                "device_uptime_sec": 334862,
                "flosense_action": "start",
                "flosense_deployment_result": "success",
                "flosense_link": "",
                "flosense_shut_off_enabled": True,
                "flosense_shut_off_level": 2,
                "flosense_state": "active",
                "flosense_version_app": "2.0.0",
                "flosense_version_model": "2.0.0",
                "fw_ver": "4.2.4",
                "fw_ver_a": "4.1.5",
                "fw_ver_b": "4.2.4",
                "ht_attempt_interval": 60000,
                "ht_check_window_max_pressure_decay_limit": 0.1,
                "ht_check_window_width": 30000,
                "ht_max_open_closed_pressure_decay_pct_limit": 2,
                "ht_max_pressure_growth_limit": 3,
                "ht_max_pressure_growth_pct_limit": 3,
                "ht_min_computable_point_limit": 3,
                "ht_min_pressure_limit": 10,
                "ht_min_r_squared_limit": 0.9,
                "ht_min_slope_limit": -0.6,
                "ht_phase_1_max_pressure_decay_limit": 6,
                "ht_phase_1_max_pressure_decay_pct_limit": 10,
                "ht_phase_1_time_index": 12000,
                "ht_phase_2_max_pressure_decay_limit": 6,
                "ht_phase_2_max_pressure_decay_pct_limit": 10,
                "ht_phase_2_time_index": 30000,
                "ht_phase_3_max_pressure_decay_limit": 3,
                "ht_phase_3_max_pressure_decay_pct_limit": 5,
                "ht_phase_3_time_index": 240000,
                "ht_phase_4_max_pressure_decay_limit": 1.5,
                "ht_phase_4_max_pressure_decay_pct_limit": 5,
                "ht_phase_4_time_index": 480000,
                "ht_pre_delay": 0,
                "ht_recent_flow_event_cool_down": 1000,
                "ht_retry_on_fail_interval": 900000,
                "ht_times_per_day": 1,
                "log_bytes_sent": 176255,
                "log_frequency": 3600,
                "mender_host": "https://mender.flotech.co",
                "motor_delay_close": 175,
                "motor_delay_open": 0,
                "motor_retry_count": 2,
                "motor_timeout": 5000,
                "pes_away_max_duration": 3600,
                "pes_away_max_pressure": 150,
                "pes_away_max_temperature": 226,
                "pes_away_max_volume": 50,
                "pes_away_min_pressure": 20,
                "pes_away_min_temperature": 36,
                "pes_away_v1_high_flow_rate": 8,
                "pes_away_v1_high_flow_rate_duration": 5,
                "pes_away_v2_high_flow_rate": 0.5,
                "pes_away_v2_high_flow_rate_duration": 5,
                "pes_home_high_flow_rate": 9.902778339386035,
                "pes_home_high_flow_rate_duration": 20,
                "pes_home_max_duration": 1738,
                "pes_home_max_pressure": 150,
                "pes_home_max_temperature": 226,
                "pes_home_max_volume": 33.851015281677256,
                "pes_home_min_pressure": 20,
                "pes_home_min_temperature": 36,
                "pes_moderately_high_pressure": 80,
                "pes_moderately_high_pressure_count": 43200,
                "pes_moderately_high_pressure_delay": 300,
                "pes_moderately_high_pressure_period": 10,
                "player_action": "disabled",
                "player_flow": 0,
                "player_min_pressure": 40,
                "player_pressure": 60,
                "player_temperature": 50,
                "power_downtime_last_24h": 0,
                "power_downtime_last_7days": 69,
                "power_downtime_last_reboot": 0,
                "reboot_count": 27,
                "reboot_count_7days": 2,
                "reboot_reason": "power_cycle",
                "s3_bucket_host": "api-bulk.meetflo.com",
                "serial_number": "294215640115",
                "system_mode": 2,
                "telemetry_batched_enabled": True,
                "telemetry_batched_interval": 300,
                "telemetry_batched_pending_storage": 30,
                "telemetry_batched_sent_storage": 30,
                "telemetry_flow_rate": 0,
                "telemetry_pressure": 78.07500375373304,
                "telemetry_realtime_change_gpm": 0,
                "telemetry_realtime_change_psi": 0,
                "telemetry_realtime_interval": 1,
                "telemetry_realtime_session_last_epoch": 0,
                "telemetry_realtime_sessions_7days": 0,
                "telemetry_realtime_storage": 7,
                "telemetry_realtime_timeout": 299,
                "telemetry_temperature": 57.00000047232966,
                "valve_actuation_count": 3465,
                "valve_actuation_timeout_count": 0,
                "valve_state": 1,
                "wifi_bytes_received": 145018827,
                "wifi_bytes_sent": 80891494,
                "wifi_disconnections": 423,
                "wifi_rssi": -61,
                "wifi_sta_enc": "psk2",
                "wifi_sta_ssid": "IP freely",
                "zit_auto_count": 233,
                "zit_manual_count": 0,
            },
            "id": TEST_DEVICE_ID,
            "macAddress": "123456abcdef",
            "nickname": "Smart Water Shutoff",
            "isPaired": True,
            "deviceModel": "flo_device_075_v2",
            "deviceType": "flo_device_v2",
            "irrigationType": "sprinklers",
            "systemMode": {
                "isLocked": False,
                "shouldInherit": True,
                "lastKnown": "home",
                "target": "home",
            },
            "valve": {"target": "open", "lastKnown": "open"},
            "installStatus": {
                "isInstalled": True,
                "installDate": "2018-08-16T02:07:39.483Z",
            },
            "learning": {"outOfLearningDate": "2018-08-16T02:07:39.483Z"},
            "notifications": {
                "pending": {
                    "infoCount": 0,
                    "warningCount": 1,
                    "criticalCount": 0,
                    "alarmCount": [{"id": 57, "severity": "warning", "count": 1}],
                }
            },
            "hardwareThresholds": {
                "gpm": {"okMin": 0, "okMax": 29, "minValue": 0, "maxValue": 35},
                "psi": {"okMin": 30, "okMax": 80, "minValue": 0, "maxValue": 100},
                "lpm": {"okMin": 0, "okMax": 110, "minValue": 0, "maxValue": 130},
                "kPa": {"okMin": 210, "okMax": 550, "minValue": 0, "maxValue": 700},
                "tempF": {"okMin": 50, "okMax": 80, "minValue": 0, "maxValue": 100},
                "tempC": {"okMin": 10, "okMax": 30, "minValue": 0, "maxValue": 40},
            },
            "serialNumber": "xxxxx",
            "connectivity": {"rssi": -61, "ssid": "IP freely"},
            "telemetry": {
                "current": {
                    "gpm": 0,
                    "psi": 78.9000015258789,
                    "tempF": 57,
                    "updated": "2020-01-16T19:01:59Z",
                }
            },
            "shutoff": {"scheduledAt": "1970-01-01T00:00:00.000Z"},
            "actionRules": [],
            "location": {"id": TEST_LOCATION_ID},
        }
    ],
    "userRoles": [{"userId": TEST_USER_ID, "roles": ["owner"]}],
    "address": "123 Main Street",
    "city": "Boston",
    "state": "MA",
    "country": "us",
    "postalCode": "12345",
    "timezone": "US/Eastern",
    "gallonsPerDayGoal": 240,
    "occupants": 2,
    "stories": 2,
    "isProfileComplete": True,
    "nickname": "Home",
    "irrigationSchedule": {"isEnabled": False},
    "systemMode": {"target": "home"},
    "locationType": "sfh",
    "locationSize": "lte_4000_sq_ft",
    "waterShutoffKnown": "unsure",
    "indoorAmenities": [],
    "outdoorAmenities": [],
    "plumbingAppliances": ["exp_tank"],
    "notifications": {
        "pending": {
            "infoCount": 0,
            "warningCount": 1,
            "criticalCount": 0,
            "alarmCount": [{"id": 57, "severity": "warning", "count": 1}],
        }
    },
    "areas": {
        "default": [
            {"id": "xxxx", "name": "Attic"},
            {"id": "xxxx", "name": "Basement"},
            {"id": "xxxx", "name": "Garage"},
            {"id": "xxxx", "name": "Main Floor"},
            {"id": "xxxx", "name": "Upstairs"},
        ],
        "custom": [],
    },
    "account": {"id": TEST_ACCOUNT_ID},
}

RESPONSE_USER_INFO_BASE = {
    "id": TEST_USER_ID,
    "email": TEST_EMAIL_ADDRESS,
    "isActive": True,
    "firstName": TEST_FIRST_NAME,
    "lastName": TEST_LAST_NAME,
    "unitSystem": "imperial_us",
    "phoneMobile": TEST_PHONE_NUMBER,
    "locale": "en-US",
    "locations": [{"id": TEST_LOCATION_ID}],
    "alarmSettings": [],
    "locationRoles": [{"locationId": TEST_LOCATION_ID, "roles": ["owner"]}],
    "accountRole": {"accountId": TEST_ACCOUNT_ID, "roles": ["owner"]},
    "account": {"id": TEST_ACCOUNT_ID},
    "enabledFeatures": [],
}

RESPONSE_USER_INFO_EXPAND_ALARM_SETTINGS = {
    "id": TEST_USER_ID,
    "email": TEST_EMAIL_ADDRESS,
    "isActive": True,
    "firstName": TEST_FIRST_NAME,
    "lastName": TEST_LAST_NAME,
    "unitSystem": "imperial_us",
    "phoneMobile": TEST_PHONE_NUMBER,
    "locale": "en-US",
    "locations": [{"id": TEST_LOCATION_ID}],
    "alarmSettings": [
        {
            "deviceId": TEST_DEVICE_ID,
            "settings": [
                {"alarmId": 4, "systemMode": "home", "smsEnabled": False},
                {"alarmId": 5, "systemMode": "away", "smsEnabled": False},
                {"alarmId": 4, "systemMode": "away", "smsEnabled": False},
                {"alarmId": 4, "systemMode": "sleep", "smsEnabled": False},
                {"alarmId": 5, "systemMode": "home", "smsEnabled": False},
                {"alarmId": 5, "systemMode": "sleep", "smsEnabled": False},
            ],
            "floSenseLevel": 5,
            "smallDripSensitivity": 4,
        }
    ],
    "locationRoles": [{"locationId": TEST_LOCATION_ID, "roles": ["owner"]}],
    "accountRole": {"accountId": TEST_ACCOUNT_ID, "roles": ["owner"]},
    "account": {"id": TEST_ACCOUNT_ID},
    "enabledFeatures": [],
}

RESPONSE_USER_INFO_EXPAND_LOCATIONS = {
    "id": TEST_USER_ID,
    "email": TEST_EMAIL_ADDRESS,
    "isActive": True,
    "firstName": TEST_FIRST_NAME,
    "lastName": TEST_LAST_NAME,
    "unitSystem": "imperial_us",
    "phoneMobile": TEST_PHONE_NUMBER,
    "locale": "en-US",
    "locations": [
        {
            "id": TEST_LOCATION_ID,
            "users": [{"id": TEST_USER_ID}],
            "devices": [{"id": TEST_DEVICE_ID, "macAddress": "606405c11e10"}],
            "userRoles": [{"userId": TEST_USER_ID, "roles": ["owner"]}],
            "address": "123 Main Stree",
            "city": "Boston",
            "state": "MA",
            "country": "us",
            "postalCode": "12345",
            "timezone": "US/Easter",
            "gallonsPerDayGoal": 240,
            "occupants": 2,
            "stories": 2,
            "isProfileComplete": True,
            "nickname": "Home",
            "irrigationSchedule": {"isEnabled": False},
            "systemMode": {"target": "home"},
            "locationType": "sfh",
            "locationSize": "lte_4000_sq_ft",
            "waterShutoffKnown": "unsure",
            "indoorAmenities": [],
            "outdoorAmenities": [],
            "plumbingAppliances": ["exp_tank"],
            "notifications": {
                "pending": {
                    "infoCount": 0,
                    "warningCount": 1,
                    "criticalCount": 0,
                    "alarmCount": [{"id": 57, "severity": "warning", "count": 1}],
                }
            },
            "areas": {
                "default": [
                    {"id": "xxxxx", "name": "Attic"},
                    {"id": "xxxxx", "name": "Basement"},
                    {"id": "xxxxx", "name": "Garage"},
                    {"id": "xxxxx", "name": "Main Floor"},
                    {"id": "xxxxx", "name": "Upstairs"},
                ],
                "custom": [],
            },
            "account": {"id": TEST_ACCOUNT_ID},
        }
    ],
    "alarmSettings": [],
    "locationRoles": [{"locationId": TEST_LOCATION_ID, "roles": ["owner"]}],
    "accountRole": {"accountId": TEST_ACCOUNT_ID, "roles": ["owner"]},
    "account": {"id": TEST_ACCOUNT_ID},
    "enabledFeatures": [],
}

RESPONSE_WATER_CONSUMPTION_INFO = {
    "params": {
        "startDate": "2020-01-16T07:00:00.000Z",
        "endDate": "2020-01-17T06:59:59.999Z",
        "interval": "1h",
        "tz": "US/Mountain",
        "locationId": TEST_LOCATION_ID,
    },
    "aggregations": {"sumTotalGallonsConsumed": 3.674},
    "items": [
        {"time": "2020-01-16T00:00:00-07:00", "gallonsConsumed": 0.04},
        {"time": "2020-01-16T01:00:00-07:00", "gallonsConsumed": 0.477},
        {"time": "2020-01-16T03:00:00-07:00", "gallonsConsumed": 0.442},
        {"time": "2020-01-16T07:00:00-07:00", "gallonsConsumed": 1.216},
        {"time": "2020-01-16T08:00:00-07:00", "gallonsConsumed": 1.499},
    ],
}

RESPONSE_WATER_METRIC_INFO = {
    "params": {
        "tz": "US/Mountain",
        "startDate": "2020-01-16T07:00:00.000Z",
        "endDate": "2020-01-17T06:59:59.999Z",
        "macAddress": "606405c11e10",
        "interval": "1h",
    },
    "items": [
        {
            "time": "2020-01-16T00:00:00-07:00",
            "averageGpm": None,
            "averagePsi": 78.3,
            "averageTempF": 59.4,
        },
        {
            "time": "2020-01-16T01:00:00-07:00",
            "averageGpm": None,
            "averagePsi": 78.2,
            "averageTempF": 59.8,
        },
        {
            "time": "2020-01-16T02:00:00-07:00",
            "averageGpm": None,
            "averagePsi": 77.8,
            "averageTempF": 61.4,
        },
    ],
}
