---
name: "Create Release"

on:
  push:
    tags:
      - "*"

jobs:
  create_release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true

  publish_to_pypi:

    runs-on: ubuntu-latest

    steps:
      - name: Publish to PyPI
        uses: abatilo/actions-poetry@v1.5.0
        with:
          args: publish --build -u __token__ -p ${{ secrets.PYPI_API_KEY }}
